'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BeheerLogging

    '''<summary>
    '''lbllogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllogin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pagAanwezigheden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagAanwezigheden As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''myBtn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''vergoeding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vergoeding As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pagGebruikers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagGebruikers As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''myBtn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''beheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beheer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''myUCScript1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myUCScript1 As Global.Olympia.CustomScriptControl

    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkbAdminTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbAdminTitle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lnkbAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbAdmin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnShowDatagrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowDatagrid As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnShowRapport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowRapport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblPeriode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fte1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte1 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''calExtStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExtStart As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblPeriodeTot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPeriodeTot As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEnd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fte7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte7 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''calExtEnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calExtEnd As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fte2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte2 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblzoektype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblzoektype As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnzoek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnzoek As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnwisfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnwisfilter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dtgDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgDataGrid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''tblFooter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFooter As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''imgbFirstbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbFirstbutton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbPrevbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbPrevbutton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbNextbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbNextbutton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbLastbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbLastbutton As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagina As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentPage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''fte99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte99 As Global.AjaxControlToolkit.FilteredTextBoxExtender

    '''<summary>
    '''lblExtraPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraPaging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UC_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Message As Global.Olympia.CustomMessage
End Class
