'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BoodschapCompose
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblVattingNummer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVattingNummer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbleenheid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbleenheid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTeam As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGebruiker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGebruiker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEenheid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEenheid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''hdCBEenheid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCBEenheid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''AutoCompleteExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AutoCompleteExtender3 As Global.AjaxControlToolkit.AutoCompleteExtender
    
    '''<summary>
    '''hdCustIDEenheid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCustIDEenheid As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''fte6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte6 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''cbTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTeam As Global.AjaxControlToolkit.ComboBox
    
    '''<summary>
    '''cbDossierBeheerder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDossierBeheerder As Global.AjaxControlToolkit.ComboBox
    
    '''<summary>
    '''lnkAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAdd As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblOntvanger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOntvanger As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtStamnummers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStamnummers As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOntvanger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOntvanger As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkbDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbDelete As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''hddStamnummerSession control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddStamnummerSession As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblOnderwerp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnderwerp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOnderwerp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnderwerp As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fte1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte1 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''lblInhoud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInhoud As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAreaInhoud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAreaInhoud As Global.System.Web.UI.HtmlControls.HtmlTextArea
    
    '''<summary>
    '''lblmaxkar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmaxkar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkSend As Global.System.Web.UI.WebControls.LinkButton
End Class
