'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class K_Andere
    
    '''<summary>
    '''lbllogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllogin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pagAanwezigheden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagAanwezigheden As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''myBtn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''vergoeding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vergoeding As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''v_jury control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_jury As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_wedstrijd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_wedstrijd As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_verplaatsing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_verplaatsing As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_andere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_andere As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''pagGebruikers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagGebruikers As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''myBtn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''beheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beheer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''myUCScript1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myUCScript1 As Global.Olympia.CustomScriptControl
    
    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblOpsteller control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpsteller As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbopsteller control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbopsteller As Global.AjaxControlToolkit.ComboBox
    
    '''<summary>
    '''lblFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfilter As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''fte2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fte2 As Global.AjaxControlToolkit.FilteredTextBoxExtender
    
    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnWisFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWisFilter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnINSERTAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnINSERTAdd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnINSERTCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnINSERTCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dtgrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgrid As Global.System.Web.UI.WebControls.DataGrid
End Class
