'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class start
    
    '''<summary>
    '''lbllogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbllogin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pagAanwezigheden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagAanwezigheden As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''myBtn1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''vergoeding control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vergoeding As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''v_lesgever control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_lesgever As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_wedstrijd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_wedstrijd As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_verplaatsing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_verplaatsing As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''v_andere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_andere As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''pagGebruikers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pagGebruikers As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''myBtn2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myBtn2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''beheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beheer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''test control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents test As Global.System.Web.UI.HtmlControls.HtmlTableCell
    
    '''<summary>
    '''lnkNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNew As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblAantalGebruikers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAantalGebruikers As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dtgDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgDataGrid As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgbFirstbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbFirstbutton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbPrevbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbPrevbutton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbNextbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbNextbutton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''imgbLastbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbLastbutton As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblPagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPagina As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCurrentPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentPage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblExtraPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtraPaging As Global.System.Web.UI.WebControls.Label
End Class
